#!/bin/sh


# Download
wget http://pecl.php.net/get/memcache-2.2.4.tgz
tar xzvf memcache-2.2.4.tgz

wget http://de.php.net/get/php-5.2.6.tar.bz2/from/bg.php.net/mirror
tar xjvf php-5.2.6.tar.bz2

wget http://php-fpm.anight.org/downloads/head/php-5.2.6-fpm-0.5.9.diff.gz
gunzip php-5.2.6-fpm-0.5.9.diff.gz

wget http://bart.eaccelerator.net/source/0.9.5.3/eaccelerator-0.9.5.3.tar.bz2
tar -xjvf eaccelerator-0.9.5.3.tar.bz2

#wget http://xaxo.eu/~space/php-fpm.conf.diff
#wget http://xaxo.eu/~space/php.ini

wget --no-check-certificate https://valio.w-co-bg.com/Data/php/php-fpm.conf.diff
wget --no-check-certificate https://valio.w-co-bg.com/Data/php/php.ini

# patch php with fpm

gunzip php-5.2.6-fpm-0.5.9.diff.gz
cd php-5.2.6
patch -p1 < ../php-5.2.6-fpm-0.5.9.diff

# install php
PHPPREFIX=/usr/local/php-5.2.6-fpm

./configure --prefix=$PHPPREFIX --enable-fastcgi --enable-fpm --with-mysql
make && sudo make install
cd ..

# install memcache

cd memcache-2.2.4
$PHPPREFIX/bin/phpize
./configure --with-php-config=$PHPPREFIX/bin/php-config
make && sudo make install
cd ..

# install eaccelerator

cd eaccelerator-0.9.5.3
$PHPPREFIX/bin/phpize
./configure --enable-eaccelerator=shared --with-php-config=$PHPPREFIX/bin/php-config
make && sudo make install
cd ..

sudo cp php.ini $PHPPREFIX/lib/

