#!/bin/sh

/sbin/modprobe ip_nat_ftp                                                                                                           
/sbin/modprobe ip_nat_irc                                                                                                           
                                                                                                                                    
/sbin/modprobe ip_conntrack_ftp                                                                                                     
/sbin/modprobe ip_conntrack_irc

echo "1" > /proc/sys/net/ipv4/ip_forward

#####################################################################
# Reject * ALL * until we setup the rules                           #
#####################################################################

# Table 'filter'
/sbin/iptables -t filter -F
/sbin/iptables -t filter -P INPUT DROP
/sbin/iptables -t filter -P OUTPUT DROP
/sbin/iptables -t filter -P FORWARD DROP

# Table 'nat'
/sbin/iptables -t nat -F
/sbin/iptables -t nat -P PREROUTING DROP
/sbin/iptables -t nat -P POSTROUTING DROP
/sbin/iptables -t nat -P OUTPUT DROP

# Table 'mangle'
/sbin/iptables -t mangle -F
/sbin/iptables -t mangle -P PREROUTING DROP
/sbin/iptables -t mangle -P OUTPUT DROP


#####################################################################
# Filters for MasK itselft	                                    #
#####################################################################

#/sbin/iptables -t mangle -A PREROUTING -i $eth1 -m tos --tos Minimize-Delay

# Full access from LAN to server interfaces
#/sbin/iptables -t filter -A INPUT -i eth0 -s 192.168.0.0/24 -d 213.91.202.150 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -i eth0 -s 192.168.0.0/24 -d 192.168.0.1 -j ACCEPT

/sbin/iptables -t filter -A INPUT -i ppp+  -j ACCEPT
/sbin/iptables -t filter -A OUTPUT -o ppp+ -j ACCEPT
/sbin/iptables -t nat -A POSTROUTING -o ppp+ -j MASQUERADE
#/sbin/iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE

#Access to VPN server (PPTPD)
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.150 --dport 1723 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.1.0/25 -d 192.168.1.4 --dport 1723 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.150 --dport 1723 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.150 --dport 1723 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.240.225.109 -d 213.91.202.150 --dport 1723 -j ACCEPT

#Access from VPN cleints
#Acess from Mimi to G4 server :P
#/sbin/iptables -t filter -A FORWARD -p tcp -s 192.168.1.16 ! -d 192.168.1.61 -j DROP

# Full access from home to server interfaces
#/sbin/iptables -t filter -A INPUT -i eth0 -s 212.104.100.19 -d 213.91.202.150 -j ACCEPT

# Allow HTTP

#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.150 --dport 80 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.202.144/28 -d 213.91.202.154 --dport 80 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 194.50.76.0/24 -d 213.91.202.154 --dport 80 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.96.70 -d 213.91.202.154 --dport 80 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -d 192.168.1.2 --dport 80 -j ACCEPT

# Allow HTTPS
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.150 --dport 443 -j ACCEPT

# Allow SSH
/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.154 --dport 22 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.117.120 -d 213.91.202.154 --dport 22 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.202.144/28 -d 213.91.202.154 --dport 22 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 194.50.76.0/24 -d 213.91.202.154 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 194.50.76.0/24 -d 194.50.76.2 --dport 22 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.1.0/25 -d 192.168.1.2 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.20 -d 213.91.202.150 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.202.144/28 -d 213.91.202.150 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.166.130 -d 213.91.202.150 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.0.1/24 -d 192.168.0.1 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.0.14 -d 192.168.0.1 --dport 22 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.0.25 -d 192.168.0.1 --dport 22 -j ACCEPT

# Allow MYSQL
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.150 --dport 3306 -j ACCEPT

# Allow FTP
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.61.111.96/27 -d 213.91.202.153 --dport 21 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.153 --dport 21 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.202.144/28 -d 213.91.202.153 --dport 21 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.0.0/24 -d 213.91.202.153 --dport 21 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.0.0/24 -d 192.168.0.1 --dport 21 -j ACCEPT

/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.154 --dport 21 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -d 192.168.1.4 --dport 21 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp --sport 20 -d 213.91.202.153 --dport 1024:65535 -j ACCEPT

# Allow Samba
/sbin/iptables -t filter -A INPUT -p udp -s 192.168.1.0/25 --dport 137:139 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.1.0/25 --dport 137:139 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p udp -s 192.168.1.0/25 --dport 445 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.1.0/25 --dport 445 -j ACCEPT

# Allow SMTP
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.151 --dport 25 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.152 --dport 25 -j ACCEPT

# Allow POP3
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.152 --dport 110 -j ACCEPT

# Allow POP3-SSL
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.150 --dport 995 -j ACCEPT

# Allow IMAP4
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.152 --dport 143 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.19 -d 213.91.202.152 --dport 143 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 212.104.100.20 -d 213.91.202.152 --dport 143 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.202.144/28 -d 213.91.202.152 --dport 143 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 213.91.166.130 -d 213.91.202.152 --dport 143 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.0.0/24 -d 213.91.202.152 --dport 143 -j ACCEPT

# Allow UDP trafic
/sbin/iptables -t filter -A INPUT -p udp -d 213.91.202.154 --sport 53 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p udp -d 194.50.76.2 --sport 53 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p udp -d 213.91.202.154 --sport 53 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p udp -d 192.168.1.2 --sport 53 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p udp -d 213.91.202.150 --sport 32768:65535 -j ACCEPT

# Allow DHCP requests in
#/sbin/iptables  -A INPUT -p udp --dport 67 --sport 68 -j ACCEPT

# Allow syslog from cisco
#/sbin/iptables  -A INPUT -p udp -s 213.91.202.158 -d 213.91.202.150 --dport 514 -j ACCEPT

# Allow DNS requests in & out
/sbin/iptables -t filter -A INPUT -p udp -d 213.91.202.154 --dport 53 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p udp -d 194.50.76.2 --dport 53 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p udp -d 213.91.202.154 --dport 53 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p udp -d 192.168.1.2 --dport 53 -j ACCEPT

# DNS TCP (zone updates):
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.150 --dport 53 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 194.50.76.2 --dport 53 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.154 --dport 53 -j ACCEPT

# Allow 3dmd monitorin from localnet
/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.1.0/25 -d 192.168.1.2 --dport 888 -j ACCEPT
########## AFPD FOR MAC USERS ####################
/sbin/iptables -t filter -A INPUT -p tcp -s 192.168.1.0/25 -d 192.168.1.2 --dport 548 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p udp -s 192.168.1.0/25 -d 192.168.1.2 --dport 548 -j ACCEPT
##################################################
# Allow ICMP messaging to propagate
#/sbin/iptables -t filter -A INPUT -p icmp -d 213.91.202.150 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p icmp -d 213.91.202.151 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p icmp -d 213.91.202.152 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p icmp -d 213.91.202.153 -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p icmp -d 194.50.76.2 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p icmp -d 213.91.202.154 -j ACCEPT
/sbin/iptables -t filter -A INPUT -p icmp -d 192.168.1.2 -j ACCEPT

# Accept packets for already established connections
/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.154 ! --syn -j ACCEPT
/sbin/iptables -t filter -A INPUT -d 213.91.202.154 -m state --state ESTABLISHED,RELATED -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.151 ! --syn -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.152 ! --syn -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.153 ! --syn -j ACCEPT
#/sbin/iptables -t filter -A INPUT -d 213.91.202.153 -m state --state ESTABLISHED,RELATED -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 213.91.202.154 ! --syn -j ACCEPT
/sbin/iptables -t filter -A INPUT -d 192.168.1.2 -m state --state ESTABLISHED,RELATED -j ACCEPT
#/sbin/iptables -t filter -A INPUT -p tcp -d 194.50.76.2 ! --syn -j ACCEPT
#/sbin/iptables -t filter -A INPUT -d 194.50.76.2 -m state --state ESTABLISHED,RELATED -j ACCEPT


# Local Host filtering (Allow to ping myself from all of my interfaces)
/sbin/iptables -t filter -A INPUT -i lo -j ACCEPT

######################################################################
# Output rules for MasK - Allow traffic only from known own IP's:   #
######################################################################
  
/sbin/iptables -t filter -A OUTPUT -s 127.0.0.1 -j ACCEPT
/sbin/iptables -t filter -A OUTPUT -s 192.168.1.2 -j ACCEPT
#/sbin/iptables -t filter -A OUTPUT -s 213.91.202.150 -j ACCEPT
#/sbin/iptables -t filter -A OUTPUT -s 213.91.202.151 -j ACCEPT
#/sbin/iptables -t filter -A OUTPUT -s 213.91.202.152 -j ACCEPT
#/sbin/iptables -t filter -A OUTPUT -s 213.91.202.153 -j ACCEPT
/sbin/iptables -t filter -A OUTPUT -s 213.91.202.154 -j ACCEPT
#/sbin/iptables -t filter -A OUTPUT -s 194.50.76.2 -j ACCEPT


######################################################################
# Forward rules (this acts as a Firewall for LAN):                   #
######################################################################

/sbin/iptables -t filter -P FORWARD ACCEPT

###############################################################################
# Change NAT policy to ACCEPT (all filtering has been done in FILTER):        #
###############################################################################

/sbin/iptables -t nat -P PREROUTING ACCEPT

/sbin/iptables -t nat -P POSTROUTING ACCEPT

/sbin/iptables -t nat -P OUTPUT ACCEPT
    
###############################################################################
# Change MANGLE policy to ACCEPT (no mangling is currently done):             #
###############################################################################
/sbin/iptables -t mangle -P PREROUTING ACCEPT
/sbin/iptables -t mangle -P OUTPUT ACCEPT


#/sbin/iptables -t nat -A POSTROUTING -o eth0 -s 192.168.1.0/25 -j MASQUERADE
    
